# Site wide configuration

title: Zwift Activity Monitor Pro
email: ruff.kevin@outlook.com
locale: en_US
logo: ActivityViewGithubRepo.png
baseurl: "/ZwiftActivityMonitor"
url: "localhost:4000"
github_username: ruffk
description: >
This application allows Zwift users to monitor their moving average power and FTP in real-time.  It also provides valuable metrics to the rider such as average and normalized power (NP), intensity factor (IF), and training stress score (TSS).  For the racer and time-trialist, there's also the ability to configure distance based splits with optional goals.
theme: minima 
